openapi: 3.0.0
info:
  title: Service A API
  version: 1.0.0
paths:
  /hello:
    get:
      responses:
        '200':
          description: A simple greeting message
          content:
            text/plain:
              schema:
                type: string
  /bye:
    get:
      responses:
        '200':
          description: A simple bye message
          content:
            text/plain:
              schema:
                type: string